language: node_js
node_js:
- '8'
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
script:
- yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: aOThgSu07qUAxlNKJJc8GU+CnQIbX+Fi7lodthkn0BjNVutxbjY6jQpoFCHwoDSzFlr1H23XnsiOC/FockHZK8OsYjV7G2vX1+O6jKOT9rMXdUkG0mMWL3FeQ0BbWWzTn3DpMiBE+3EYCaLrU1Uns7fi7KAPGonb1AKrVdPCo3cB6PDFAFCOWZrtYHCQJSDZHrI16s1Q+CJ/hy4o8Jg9Olr1ZQbzYo2nCOyeRohKZzK/4tU87l5bULXZF3vn9hwd7r7UHDM7s3Liy4A2rOa6C62z/RmC5ASRJ4c9QWAVTGJgp97G8MkBmuodztfx3rqPE0J1GB9OGMnT14hi0KhcR+eX2Q0MhtPDp1xqJ8/f6TDUmVV9yNNtT237LbsSeQb/W8xb94wIbL4x9L8zIcniwPblxHObGUsvGf+hLqJ0AO9sSL+ASajA6pP+1BjfUKY9664ySWEsRYS74OCNLDeQdPVRCp4MqaqSRQulmeslviwlDGXEgJ88mULJwTDHyfWH2TJqp/DCfR2nr6gnhwnUYtzBOZBDp1uZ0ZZt4TOM714r9g6+RlCTFe2jF6nW9u5Co+bScK467YOTy25D2pknv8k+g2ZXzN+6eoLR0YbkaVlWPPW6o1hbwXcMQbwe42QlKIlmVf+BxZ+NcqLdf9V1PyrjEl0XDEdQ6m9NwRaMIqY=
