language: node_js
node_js:
- '8'
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
script:
- yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: BYPbP7qK2DwNvx9sMP2WSG1kyrO5jyqHsoYVqM9Y9HmAH3VGdEyZiNZDi7Uxfw5l/Zry/wNeoYI+NyZ672pVxQSObbIjO9wjjjgsP86lc0YueR+VO5/bVIAKVIGEOqyKfXkjSFptQgBbpAoSpld9fb9B8HVZTQAB49P3hTb0CzKUS+y/3XfyhBS/gZ0sjLlBZp1B1uUcwoavmtDzjsJW8t1n8kmt2wdA4X9httooMHf5jNX/eHZYH2DMBbHILQY3zPo0X0GGE8g7yqtrf0fE5Llj0wQEKn4l3Vo0GltySpGEVjGwn/1J2OHtoe3yOS03Y5LfnYSliUL0tKGd+Ln6hgq8+bCoxWZXhHJAgf/XemONSz9Y2vHB/JPgDZ+PiWOQvEm6kE7jnIs1CLytvIEBvYlgSQVbzORahO2an40n3EJNHHzfaAvsUdMaMgW+22U9vvBryAoxGVD7E5X7kPbbdDAxGEO29/AwGQJTRl379M5Y3vnrEFeqby6m09pd0VSJlqIuyj9EUHM51MF8NEfa0IaCwX4UB+yKBk5SuWNpC1/whbaDZHTU2rm/qPt08Zrw9v5vV/twNkE23gkmOP/OXdVLWJqSQKoQ3A9VT5SV8sfUScJ+DxThtXe/Z3Cc4hPm4Hfk3sQaNXvmxmBFTYt6hlpfkxRjL8nKkBrUStSOQ2A=

