language: node_js
node_js:
- '8'
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
script:
- yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: OSbexBGqe/Da282VZBFcmPhCFHsvy/+ZyeWdgCa4/5xNQ3i/n97o7lwTEl8LNEjb7ZQzb9zOWs+uHNXtRPEvx9lBea8oHOTFkLy6y0zt6hYJQtWRF92GOKPIEur5Y/LOBipLqIlQ0b0nNQUC/g9ba2jyAczjoAtNpgf+fV3PAErffVWwX3XRK8+zvE09Gt1zoVb1b8uuetWT0Oyvoe6rQ+CSGuYNzKjG5epKIPgOjkMAwGnt6+1EjkKSWXHnC5H8c+XtqhEQKTNDzaf1cLjiY8uYmzwGXJ5TDnlIo2zzBDdZRXs+V1as8JjTHcvR30BjLUacsyDCIxvSDsAzfxawr83OhnkYyLQkKYUQuR8SnDxT5RiBTHvbGt/9pn2AKtzwqWEXSK9buEnqrc7f0dzbKekhFlTAP4jVrQOhomrvwKOki81aFnpond/09cH1jeNx4lgo+wp13o3aailEIHHmF/WqI6LT7KuXT4wMo6CAijHyrf24+6RT99glh+7iWGCXwDn3yYUCcEk8DjIc/5rrH+f0Nls9b5Qnp5fDUUs0Ws6YmXxYVEUE8kei4nqIGhk41yDQN3AMG6/zBRB/53NT6WQtDNIz8Y0wIe2R92Ti7eygHyr9ZJpWE35lLmgs2uAYmK2k9qWCNGajGLgTPu0WaRZGIeSZY7NLhC3Hg7ylfw4=
